### ISSUE TITLE
1.17假人无法召唤

### ISSUE THREAD

**Issue by TaiChi01** [Jerry-FaGe/MCDR-BotKikai#1]
Windows10
Python3.9
Minecraft：1.17
该插件，无法在游戏了 召唤假人
后台报错如此
![image](https://user-images.githubusercontent.com/28525186/123595747-d988ac80-d823-11eb-9eee-f34215a03573.png)

**Comment by Jerry-FaGe** [comment]
由于我并没有1.17的服务端，而且提供的信息过于笼统，我没有办法定位问题出在哪里

麻烦请提供更详细的信息：
- 是否有地毯mod
- 使用的命令
- 详细的控制台的输出
- 对应的假人的配置文件
- 直接在聊天框输入`/player XXX spawn`是否可以正常召唤假人

**Comment by TaiChi01** [comment]
> 由于我并没有1.17的服务端，而且提供的信息过于笼统，我没有办法定位问题出在哪里
> 
> 麻烦请提供更详细的信息：
> 
> * 是否有地毯mod
> * 使用的命令
> * 详细的控制台输出
> * 对应假人的配置文件
> * 直接在聊天框输入`/player XXX spawn`是否可以正常召唤假人

- 1. 有地毯端,/player xxx spawn 可以正常召唤
- 2. 使用的命令是!!bk xxx spawn其他命令也均无反应
- 3. 详细的控制台输出https://paste.ubuntu.com/p/pTN7HK5qz5/
- 4. 对应假人的配置文件https://paste.ubuntu.com/p/FwNh45svBF/

**Comment by Jerry-FaGe** [comment]
> 不行我都写这么多了不能白写，发出来也给后来者提个醒。

在配置文件中：

- \<name\> 表示的是这是一个指代`名字`的参数（这个名字应该是MC玩家中所存在的名字），配置文件中所有的 \<name\> 应该替换成你想召唤的假人名字
- \<kikai\> 表示的是这是一个指代`昵称`的参数，配置文件中所有的 \<kikai\> 应该替换成你想在指令中输入什么 昵称/简写/汉语 来召唤这个假人
- !!bk 系列指令只能召唤配置文件中存在设定的假人

综上所述，你的配置文件可以改成

```Json
 {
    "steve": {
        "nick": [
            "steve",
            "史蒂夫",
            "SDF",
            "1号假人"
        ],
        "dim": "minecraft:overworld",
        "pos": [
            39.5,
            65,
            106.5
        ],
        "facing": "0 0"
    },
    "alex": {
        "nick": [
            "alex",
            "艾利克斯",
            "2号假人"
        ],
        "dim": "minecraft:overworld",
        "pos": [
            48.05148373211992,
            67,
            159.59332582552295
        ],
        "facing": "-123.15028 9.899961"
    }
}
```
这样，你就可以通过输入指令 `!!bk steve spawn` 或者 `!!bk 史蒂夫 spawn` 或者 `!!bk SDF spawn` 或者 `!!bk 1号假人 spawn` 来在配置文件所指定的位置召唤一个名为 `steve` 的假人。同时，也可以通过输入指令 `!!bk alex spawn` 或者 `!!bk 艾利克斯 spawn` 或者 `!!bk 2号假人 spawn` 来在配置文件所指定的位置召唤一个名为 `alex` 的假人。

**另外建议仔细阅读本插件的 README ，里面对于如何使用如何配置都有较为详细的讲解。**
