### ISSUE TITLE
游戏内按键

### ISSUE THREAD

**Issue by Adogs1** [Jerry-FaGe/MCDR-BotKikai#3]
![QQ截图20231117225753](https://github.com/Jerry-FaGe/MCDR-BotKikai/assets/111733210/03a9d6e5-6353-4e31-8e1d-94c4759349b8)
如图suo's所示，这三个按键它无法使用

**Comment by Jerry-FaGe** [comment]
我不确定这个插件是否完美支持现在的 MCDR 2.0，2.0 之后我就没有维护了（因为服务器没了而且懒得啃文档 XD）。我大概看过2.0的插件仓库，里面有更加完善的 bot 插件，如果你对名称映射相关的功能没有需求的话可以转用那个插件。

**Comment by Adogs1** [comment]
> 我不确定这个插件是否完美支持现在的 MCDR 2.0,2.0 之后我就没有维护了（因为服务器没了，而且懒得啃文档 XD）。我大概看过2.0的插件仓库，里面有更加完善的 bot 插件，如果你对名称映射相关的功能没有需求的话可以转用那个插件。

我自己看看文档吧，目前就RText命令有点问题

**Comment by Adogs1** [comment]
> 我不确定这个插件是否完美支持现在的 MCDR 2.0,2.0 之后我就没有维护了（因为服务器没了，而且懒得啃文档 XD）。我大概看过2.0的插件仓库，里面有更加完善的 bot 插件，如果你对名称映射相关的功能没有需求的话可以转用那个插件。

它能完美适配MCDR2.X，按键无法使用的原因是1.19引入的游戏内限制，目前可通过Mod修复到1.19以前
